name: b.el Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - 24.4
          - 29.0
          - snapshot
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - name: Set up Emacs
      uses: purcell/setup-emacs@v4.0
      with:
        version: ${{ matrix.emacs_version }}

    - name: Test
      run: |
        bin/setup.sh
        bin/tests.sh

  # docs:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: purcell/setup-emacs@v4.0
  #       with:
  #         version: 28.1
  #     - name: Generate documentation
  #       run: |
  #         bin/setup.sh
  #         echo " Test Doc generation..."
  #         bin/docs.sh
  #         echo "════════════════════════════════════════════════════════════════════════════════"
